### ISSUE TITLE
ModuleNotFoundError: No module named 'forwarder.config'

### ISSUE THREAD

**Issue by jerung3000** [keselekpermen69/Telegram_Forwarder#28]
ok..already follow the step but there were statements show like this

C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder>python -m forwarder
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in get_module_details
import(pkg_name)
File "C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder\forwarder_init.py", line 42, in
from forwarder.config import Development as Config
ModuleNotFoundError: No module named 'forwarder.config'

**Comment by keselekpermen69** [comment]
Please check the readme again.
Configuration steps was described there.

you need to **create** a file named `config.py` (at the same level with `sample_config.py`)  **not changing** the name of `sample_config.py`.
